version: '3.7'

services:

  BACKEND_SERVER:
    image: publicissapient1905.azurecr.io/hybrissap1905:v01
    restart: on-failure
    container_name: hybris
    ports:
     - 9001-9003:9001-9003
    sysctls:
      - kernel.shmmax=1073741824
      - kernel.shmmni=524288
      - kernel.shmall=8388608
      - net.ipv4.ip_local_port_range=40000 60999
    ulimits:
      nproc: 65535
      nofile:
        soft: 1048576
        hard: 1048576

volumes:
  hybris_data:
    driver: local
